/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicioPilas;

/**
 * Esta clase representa una interfaz grafica que simula el funcionamiento de 
 * una pila con operacones basicas: push, pop, peek y mostrar
 * 
 * Pero esta se apoya de la clase MiStack, esta se encraga de manejar 
 * internamente la estrcutura de los datos
 * @author Romero
 */
public class SimulacionPilasGrafico extends javax.swing.JFrame {
    // Objeto que representa la pila con capacidad de 5 elementos
    private final MiStack pila = new MiStack(5);
    

   
    public SimulacionPilasGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPush = new javax.swing.JButton();
        BtnPop = new javax.swing.JButton();
        BtnPeek = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtElementos = new javax.swing.JTextField();
        LblEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPush.setText("Push");
        BtnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPushActionPerformed(evt);
            }
        });

        BtnPop.setText("Pop");
        BtnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPopActionPerformed(evt);
            }
        });

        BtnPeek.setText("Peek");
        BtnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeekActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblTitulo.setText("Simulador de pila");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText(" Elemento:");

        LblEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtArea.setColumns(20);
        TxtArea.setRows(5);
        jScrollPane1.setViewportView(TxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(LblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPeek, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPush)
                    .addComponent(BtnPop)
                    .addComponent(BtnPeek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Es el evento del boton push
     * @param evt permite agragr un nuevo elemto al tope de pila
     */
    private void BtnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPushActionPerformed
     String valor = TxtElementos.getText().trim();
    if (valor.isEmpty()) {
        LblEstado.setText("Ingresa un valor antes de hacer Push.");
        return;
    }

    boolean ok = pila.push(valor);
    if (ok) {
        LblEstado.setText("Elemento agregado: " + valor);
        TxtElementos.setText("");
        mostrarPila();
    } else {
        LblEstado.setText("La pila está llena.");
    }
    }//GEN-LAST:event_BtnPushActionPerformed
    /**
     * Evenot del boton pop
     * @param evt este extrae el elemto del tope de al pila, si exite y lo muetra 
     */
    private void BtnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPopActionPerformed
     String valor = pila.pop();
    if (valor.isEmpty()) {
        LblEstado.setText("La pila está vacía.");
    } else {
        LblEstado.setText("Elemento eliminado: " + valor);
        mostrarPila();
    }
    }//GEN-LAST:event_BtnPopActionPerformed
    /**
     * Evento del bototn peek
     * @param evt muestra cual es el elemto que se encuentra actualmente en el
     * tope sin eliminarlo de la pila
     */
    private void BtnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeekActionPerformed
      String valor = pila.peek();
    if (valor.isEmpty()) {
        LblEstado.setText("La pila está vacía.");
    } else {
        LblEstado.setText("Tope actual: " + valor);
    }
    }//GEN-LAST:event_BtnPeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulacionPilasGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulacionPilasGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulacionPilasGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulacionPilasGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulacionPilasGrafico().setVisible(true);
            }
        });
    }
 /**
 * Muestra el contenido actual de la pila en el área de texto
 */
private void mostrarPila() {
    TxtArea.setText("");
    String[] datos = pila.viewStack();

    if (datos.length == 0) {
        TxtArea.setText("La pila está vacía.");
        return;
    }
    // Se muestran los elementos desde el tope hacia la base
    for (int i = 0; i < datos.length; i++) {
        TxtArea.append("[" + (datos.length - 1 - i) + "] " + datos[i] + "\n");
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPeek;
    private javax.swing.JButton BtnPop;
    private javax.swing.JButton BtnPush;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextArea TxtArea;
    private javax.swing.JTextField TxtElementos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
