/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciosColas;

/**
 *
 * @author Romero
 */
// Importa la clase JOptionPane del paquete javax.swing.
// Sirve para mostrar mensajes o alertas emergentes en pantalla.
import javax.swing.JOptionPane;
public class SimulacionCola extends javax.swing.JFrame {
    
    private String[] cola = new String[5]; // cola de 5 posiciones
    private int frente = 0; // índice del primer elemento
    private int fin = 0;    // índice donde se insertará el siguiente
    private int tamaño = 0; // cantidad de elementos en la cola

 
    public SimulacionCola() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        LblElemento = new javax.swing.JLabel();
        TxtElemento = new javax.swing.JTextField();
        BtnOffer = new javax.swing.JButton();
        BtnPoli = new javax.swing.JButton();
        BtnPeek = new javax.swing.JButton();
        LblEstado = new javax.swing.JLabel();
        TxtPos1 = new javax.swing.JTextField();
        TxtPos2 = new javax.swing.JTextField();
        TxtPos3 = new javax.swing.JTextField();
        TxtPos4 = new javax.swing.JTextField();
        TxtPos5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblTitulo.setText("Simulacion de cola");

        LblElemento.setText("Elemento:");

        BtnOffer.setText("Offer");
        BtnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOfferActionPerformed(evt);
            }
        });

        BtnPoli.setText("Poll");
        BtnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPoliActionPerformed(evt);
            }
        });

        BtnPeek.setText("Peek");
        BtnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeekActionPerformed(evt);
            }
        });

        LblEstado.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(LblElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BtnOffer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnPeek)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(BtnPoli))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtPos1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPos4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPos5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblElemento)
                    .addComponent(TxtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOffer)
                    .addComponent(BtnPoli)
                    .addComponent(BtnPeek))
                .addGap(50, 50, 50)
                .addComponent(LblEstado)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Agrega el valor escrito en el cuadro de texto al final de la cola.
    // Si la cola está llena, muestra un mensaje de advertencia y no agrega nada.
    private void BtnOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOfferActionPerformed
         String valor = TxtElemento.getText().trim();

        // Validar cuadro vacío
        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor para agregar.");
            return;
        }

        // Verificar si la cola está llena
        if (tamaño == 5) {
            JOptionPane.showMessageDialog(this, "La cola está llena.");
            LblEstado.setText("Estado: Cola llena");
            return;
        }

        // Insertar en la cola
        cola[fin] = valor;
        fin = (fin + 1) % 5; // avanzar circularmente
        tamaño++;

        // Actualizar interfaz
        actualizarCola();
        TxtElemento.setText("");
        LblEstado.setText("Estado: Se agregó " + valor);
    }//GEN-LAST:event_BtnOfferActionPerformed
     // Extrae (elimina) el primer elemento de la cola y lo muestra
     // en el cuadro de texto. Recorre los demás valores hacia el inicio.
     // Si la cola está vacía, muestra una advertencia y no realiza la acción.
    private void BtnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPoliActionPerformed
           // Verificar si la cola está vacía
        if (tamaño == 0) {
            JOptionPane.showMessageDialog(this, "La cola está vacía.");
            LblEstado.setText("Estado: Cola vacía");
            return;
        }

        // Obtener y eliminar el primer elemento
        String valor = cola[frente];
        cola[frente] = null;
        frente = (frente + 1) % 5; // avanzar circularmente
        tamaño--;

        // Mostrar en el cuadro
        TxtElemento.setText(valor);
        actualizarCola();
        LblEstado.setText("Estado: Se extrajo " + valor);
    }//GEN-LAST:event_BtnPoliActionPerformed
    // Muestra el primer valor de la cola sin eliminarlo.
    // Lo enseña en una ventana emergente para evitar duplicados.
    // Si la cola está vacía, muestra una advertencia.
    private void BtnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeekActionPerformed
        // Verificar si está vacía
    if (tamaño == 0) {
        JOptionPane.showMessageDialog(this, "La cola está vacía.");
        LblEstado.setText("Estado: Cola vacía");
        return;
    }

    // Mostrar el primer elemento sin eliminarlo
    JOptionPane.showMessageDialog(this, "Elemento al frente: " + cola[frente]);
    LblEstado.setText("Estado: Frente → " + cola[frente]);
    }//GEN-LAST:event_BtnPeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulacionCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulacionCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulacionCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulacionCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulacionCola().setVisible(true);
            }
        });
    }
    //Este metodo actuaiza la interfaz
    private void actualizarCola() {
        // Mostrar los valores en los cuadros según el orden real
        String[] temp = new String[5];
        for (int i = 0; i < tamaño; i++) {
            temp[i] = cola[(frente + i) % 5];
        }

        TxtPos1.setText(temp[0] != null ? temp[0] : "");
        TxtPos2.setText(temp[1] != null ? temp[1] : "");
        TxtPos3.setText(temp[2] != null ? temp[2] : "");
        TxtPos4.setText(temp[3] != null ? temp[3] : "");
        TxtPos5.setText(temp[4] != null ? temp[4] : "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOffer;
    private javax.swing.JButton BtnPeek;
    private javax.swing.JButton BtnPoli;
    private javax.swing.JLabel LblElemento;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtElemento;
    private javax.swing.JTextField TxtPos1;
    private javax.swing.JTextField TxtPos2;
    private javax.swing.JTextField TxtPos3;
    private javax.swing.JTextField TxtPos4;
    private javax.swing.JTextField TxtPos5;
    // End of variables declaration//GEN-END:variables
}
